namespace ZIPCodePH.Data.Old.Models;

public static class AreaModel
{
    public static IEnumerable<string> Ncr = new[]
    {
        "Manila",
        "Caloocan",
        "Las Piñas",
        "Makati",
        "Malabon",
        "Mandaluyong",
        "Marikina",
        "Muntinlupa",
        "Navotas",
        "Parañaque",
        "Pasay",
        "Pasig",
        "Pateros",
        "Quezon City",
        "San Juan",
        "Taguig",
        "Valenzuela",
    };

    public static IEnumerable<string> Luzon = new[]
    {
        "Abra",
        "Albay",
        "Apayao",
        "Aurora",
        "Bataan",
        "Batanes",
        "Batangas",
        "Benguet",
        "Bulacan",
        "Cagayan",
        "Camarines Norte",
        "Camarines Sur",
        "Catanduanes",
        "Cavite",
        "Ifugao",
        "Ilocos Norte",
        "Ilocos Sur",
        "Isabela",
        "Kalinga",
        "La Union",
        "Laguna",
        "Marinduque",
        "Masbate",
        "Mountain Province",
        "Nueva Ecija",
        "Nueva Vizcaya",
        "Occidental Mindoro",
        "Oriental Mindoro",
        "Palawan",
        "Pampanga",
        "Pangasinan",
        "Quezon",
        "Quirino",
        "Rizal",
        "Romblon",
        "Sorsogon",
        "Tarlac",
        "Zambales",
    };

    public static IEnumerable<string> Visayas = new[]
    {
        "Aklan",
        "Antique",
        "Biliran",
        "Bohol",
        "Capiz",
        "Cebu",
        "Eastern Samar",
        "Guimaras",
        "Iloilo",
        "Leyte",
        "Negros Occidental",
        "Negros Oriental",
        "Northern Samar",
        "Samar",
        "Siquijor",
        "Southern Leyte",
    };

    public static IEnumerable<string> Mindanao = new[]
    {
        "Agusan del Norte",
        "Agusan del Sur",
        // "Alabeln",
        "Basilan",
        "Bukidnon",
        "Camiguin",
        "Compostela Valley",
        "Davao del Norte",
        "Davao del Sur",
        "Davao Occidental",
        "Davao Oriental",
        "Dinagat Islands",
        "Lanao del Norte",
        "Lanao del Sur",
        "Maguindanao",
        "Misamis Occidental",
        "Misamis Oriental",
        "North Cotabato",
        "Sarangani",
        "South Cotabato",
        "Sultan Kudarat",
        "Sulu",
        "Surigao del Norte",
        "Surigao del Sur",
        "Tawi-Tawi",
        "Zamboanga del Norte",
        "Zamboanga del Sur",
        "Zamboanga Sibugay",
    };
}